version: "3.3"
services:
  nodeserver-communication:
    container_name: nodeserver-communication
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:local
    ports:
      - 3010:3010
    env_file:
      - .env.example
    depends_on:
      - mongo
    networks:
      - my_network

  mongo:
    container_name: mongo
    image: mongo:4.0
    volumes:
        - ./../mongodb/data:/data/db
    ports:
      - 27017:27017
    networks:
      - my_network
networks:
  my_network:
    name: my_network
    external: true
