version: "3.3"
services:
  nodeserver-communication:
    container_name: nodeserver-communication
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:local
    ports:
      - 3010:3010
    env_file:
      - .env.example
    depends_on:
      - mysqlprisma
    networks:
      - my_network

  mysqlprisma:
    image: mysql:8.0
    container_name: mysqlprisma
    ports:
      - 3306:3306
    env_file:
      - .env.example
    volumes:
      - /var/lib/mysql
    networks:
      - my_network
networks:
  my_network:
    name: my_network
    external: true
