version: "3.3"
services:
  nodeserver:
    container_name: nodeserver
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=${NODE_ENV}
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    environment:
      - GOOGLE_PUBSUB_TOPIC_NAME=${GOOGLE_PUBSUB_TOPIC_NAME}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - PORT=${PORT}
      - MONGO_URL=${MONGO_URL}
      - NODE_ENV=${NODE_ENV}
      - MS_COMMUNICATION_SENDGRID_API_KEY=${MS_COMMUNICATION_SENDGRID_API_KEY}
      - MS_COMMUNICATION_ZENVIA_API_KEY=${MS_COMMUNICATION_ZENVIA_API_KEY}
      - MS_COMMUNICATION_ZENVIA_NUMBER=${MS_COMMUNICATION_ZENVIA_NUMBER}
    depends_on:
      - mongo
  mongo:
    container_name: vss-mongo
    image: mongo:4.0
    volumes:
        - ./../mongodb/data:/data/db
    ports:
      - "27017:27017"
