version: "3.3"
services:
  nodeserver-communication:
    container_name: nodeserver-communication
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=local
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    command: npm run start:local
    env_file:
      - .env
    depends_on:
      - mongo
    links:
      - "mongo"
    networks:
      - my_network
    ports:
      - 3000:3000
  mongo:
    container_name: mongo
    image: mongo:4.0
    volumes:
        - ./../mongodb/data:/data/db
    ports:
      - 27017:27017
    networks:
      - my_network
networks:
  my_network:
    external:
      name: my_network
