apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
    run.googleapis.com/ingress-status: internal-and-cloud-load-balancing
  labels:
    cloud.googleapis.com/location: southamerica-east1
  name: vale-saude-ms-comunicacao
  namespace: '86061648839'
  selfLink: /apis/serving.knative.dev/v1/namespaces/86061648839/services/vale-saude-ms-comunicacao
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/vpc-access-connector: vss-serverless-connector
        run.googleapis.com/vpc-access-egress: private-ranges-only
      labels:
        run.googleapis.com/startupProbeType: Default
      name: vale-saude-ms-comunicacao-00001-liq
    spec:
      containerConcurrency: 1
      containers:
        - image: southamerica-east1-docker.pkg.dev/dev-amazonia-vidav-vale-saude/dev-amazonia-vidav-vale-saude-registry/vidav-vale-saude-ms-communication:1.0.0
          ports:
            - containerPort: 80
              name: http1
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
          startupProbe:
            failureThreshold: 1
            periodSeconds: 240
            tcpSocket:
              port: 80
            timeoutSeconds: 240
      serviceAccountName: 86061648839-compute@developer.gserviceaccount.com
      timeoutSeconds: 30
  traffic:
    - latestRevision: true
      percent: 100
