apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
    run.googleapis.com/ingress-status: internal-and-cloud-load-balancing
  labels:
    cloud.googleapis.com/location: southamerica-east1
  name: vidav-vale-saude-ms-communication
  namespace: '86061648839'
  selfLink: /apis/serving.knative.dev/v1/namespaces/86061648839/services/vidav-vale-saude-ms-communication
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/vpc-access-connector: vss-serverless-connector
      labels:
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 1
      containers:
        - image: southamerica-east1-docker.pkg.dev/dev-amazonia-vidav-vale-saude/dev-amazonia-vidav-vale-saude-registry/vidav-vale-saude-ms-communication:1.0.0
          ports:
            - containerPort: 80
              name: http1
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
          startupProbe:
            failureThreshold: 1
            periodSeconds: 240
            tcpSocket:
              port: 80
            timeoutSeconds: 240
          env:
            - name: MS_COMMUNICATION_PGMAIS_URL
              value: https://apicanais.pgmais.io/v1/apps
            - name: NODE_ENV
              value: dev
            - name: MS_COMMUNICATION_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: '1'
                  name: MS_COMMUNICATION_DATABASE_URL
            - name: MS_COMMUNICATION_SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  key: '1'
                  name: MS_COMMUNICATION_SENDGRID_API_KEY
            - name: MS_COMMUNICATION_PGMAIS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: '1'
                  name: MS_COMMUNICATION_PGMAIS_TOKEN
      serviceAccountName: 86061648839-compute@developer.gserviceaccount.com
      timeoutSeconds: 30
  traffic:
    - latestRevision: true
      percent: 100
